config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  get  '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/help', :to => 'pages#help'
  get '/signup', :to => 'users#new'

  root :to => 'pages#home'

  

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
#  attr_accessible :nom, :email, :password, :password_confirmation
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :nom, :presence => true,
                  :length => {:maximum => 50}
  validates :email, :presence => true,
                    :format => email_regex,
                    :uniqueness => {:case_sensitive => false}
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40}
  before_save :encrypt_password

  #Retourne vrai si le mot de passe correspond
  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "About"
  end

  def help
    @titre = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @titre = "Inscription"
  end

  def show
    @user = User.find(params[:id])
    @titre = @user.nom
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # retourner un titre basé sur la page
  def titre
    base_titre = "Default title :"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def logo
    @logo = image_tag("logo.png", :alt => "Application exemple", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {:size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class = "round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tuto</a></li>
    </ul>
  </nav>
  </footer>

app/views/layouts/_header.html.erb
      <header>
      <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Accueil", root_path %></li>
            <li><%= link_to "Aide", help_path %></li>
            <li><%= link_to "Inscription", signup_path %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <%= stylesheet_link_tag 'blueprint/custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class = "round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
  <h1>About</h1>
  <p>
    About Ruby on Rails Tutorial à propos de l'Application Exemple à
    <a href="http://railstutorial.org/feedback">feedback page</a>.
  </p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      Contact Ruby on Rails Tutorial à propos de l'Application Exemple à
      <a href="http://railstutorial.org/feedback">feedback page</a>.
    </p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>Contenu de l'aide :
  <a href = "http://railstutorial.org/help">page d'aide</a>
</p>

app/views/pages/home.html.erb
    <h1>Application exemple</h1>
    <p>
      Page d'accueil de l'application
       <a href="http://railstutorial.org/">RoR tutoriel</a>
    </p>
    <%= link_to "S'inscrire", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class ="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>